language: python
python:
  - '3.6'
script:
  - echo 'override'
deploy:
  provider: pypi
  user: jacobi
  on:
    branch: master
    tags: true
  password:
    secure: kOlagv5yK7lCxz8Ck5k2K4IdQBAuJVNEUrWZSyhvswYNMlnY1fiArXTwHSy9Bdt04D3R9mVpdyXTsQEnJedP0DWjYLeNBBM6uYD3eckjXQDnWjBpdILJ3nyo8dqzfAeRbkTKVCFEX9IvHm3bUmkoGyc3mPasuZs+gusijVoXWpxoL2z/DQeGU1ZfoNDzTPvh9OTKxPCfAXJ78VTpKxnJtykKxz6YIr3ziQnoBzGyNCTmbqkUYMdBx4UM8NDbbBYwv8qvddqvCvci5TQ1hXESFTzLp/bryfWnqju1nKrg9J9DhmQase8k2EJF3dV49n4uLosIJ/u5H29+wDyLRJqHZ1aOc2zogTbyDV5EgWL1nSeVqsqkISiZIU82PEkgy/MNKYWVOU1FwDmhQzhWLNk5Dbp9loqPBdyWV2zob+a2q7L8GY8e2Xazk2GqUAuQwvoePr5tewE2V2c7D2xicx9baD+fj3REhK3BiQvbvJE16UA0FjtT6te6xGiUv+8kGYs91/wHlylw+U5ASvEIpWUFyO2e0zBsqnAKSRf7e77XhQabE7MQx297d/gSrxC7OAPP5ZiEMjddStIjDGFLT/mVv7yEhpfyi88uDW7IEsv8IumqNdzMnN+w0gXitgNtwPzjIIQrsW6fc33nfFckZbldjk6hh27GXI0I2tVQVUV6GFo=
